name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
template: |
  ## Changes

  $CHANGES

categories:
  - title: "Features"
    labels:
      - "enhancement"
      - "feature"
  - title: "Fixes"
    labels:
      - "bug"
      - "fix"
  - title: "Maintenance"
    labels:
      - "chore"
      - "dependencies"

change-template: "- $TITLE (#$NUMBER) @$AUTHOR"
no-changes-template: "- No user-facing changes in this release."

version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "enhancement"
      - "feature"
  patch:
    labels:
      - "bug"
      - "fix"
      - "chore"
      - "dependencies"
  default: patch

