name: Shell Lint

on:
  pull_request:
    paths:
      - "scripts/**"
      - ".github/workflows/**"
  push:
    branches:
      - main
    paths:
      - "scripts/**"
      - ".github/workflows/**"

permissions:
  contents: read

jobs:
  shellcheck:
    name: shellcheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Shellcheck scripts
        uses: ludeeus/action-shellcheck@2.0.0
        with:
          scandir: "./scripts"

